### ISSUE TITLE
Update the repo to have a model-card.md template and a data-statement.md template.

### ISSUE THREAD

**Issue by vukosim** [dsfsi/dsfsi-project-starter#1]
We need to update our project starter to have
- [ ] Model Card MD File Template 
- [ ] Or Link to a Model Card Generator like https://huggingface.co/docs/huggingface_hub/guides/model-cards
- [ ] Data Statement Card Template [Maybe borrowing from this https://github.com/TechPolicyLab/Data-Statements]

We should acknowledge where we get the resources

Update the README.md as well.

**Comment by lastrucci01** [comment]
Hey @fiskanibanda, I feel like this issue has been done? :))

**Comment by fiskanibanda** [comment]
Completed.
